services:
  - type: web
    name: screen-share
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: LEPTOS_ENV
        value: PROD
      - key: LEPTOS_OUTPUT_NAME
        value: screen_share
      - key: LEPTOS_SITE_ROOT
        value: site
      - key: LEPTOS_SITE_PKG_DIR
        value: pkg
