/* auto-generated by NAPI-RS */
/* eslint-disable */

export interface AudioProcessInfo {
  pid: number
  exeName: string
}

/**
 * Resolves a `hwnd` — the numeric part of the `window:<hwnd>:0` source id
 * Chromium's `desktopCapturer` reports — to the process that owns that
 * window.
 */
export declare function getPidForWindow(hwnd: number): number | null

/**
 * Resolves any live PID to its executable's file name — works for any
 * process, not just ones with an active WASAPI session.
 */
export declare function getExeNameForPid(pid: number): string | null

/**
 * Every process WASAPI currently reports as having an active
 * render-audio session, one entry per distinct resolved executable name.
 */
export declare function listActiveAudioProcesses(): Array<AudioProcessInfo>

/**
 * A running audio-loopback share: continuously mixes together every
 * currently-active WASAPI session whose resolved executable name passes
 * `mode`/`targetName`/`excludedNames`, delivering interleaved f32 stereo
 * PCM chunks to `onChunk` roughly every 20ms until `stop()` is called.
 */
export declare class WindowsAudioSession {
  constructor()
  /**
   * `mode` is `"window"` (only `targetName`'s audio) or `"screen"`
   * (everything except `excludedNames`).
   */
  start(
    mode: string,
    targetName: string | null,
    excludedNames: Array<string>,
    onChunk: (err: Error | null, result: Buffer) => void,
  ): void
  /**
   * Stops every per-process capture, the mixer, and the poll loop, and
   * blocks until all of their threads have actually exited.
   */
  stop(): void
}
