/* auto-generated by NAPI-RS */
/* eslint-disable */

const { existsSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let loadError = null

if (platform === 'win32' && arch === 'x64') {
  const localFile = join(__dirname, 'windows-audio.win32-x64-msvc.node')
  try {
    nativeBinding = existsSync(localFile)
      ? require(localFile)
      : require('@screen-share/windows-audio-win32-x64-msvc')
  } catch (e) {
    loadError = e
  }
} else {
  loadError = new Error(
    `windows-audio: unsupported platform/arch: ${platform}/${arch} (this native module is Windows x64-only)`,
  )
}

if (!nativeBinding) {
  throw loadError ?? new Error('windows-audio: failed to load native binding')
}

module.exports.getPidForWindow = nativeBinding.getPidForWindow
module.exports.getExeNameForPid = nativeBinding.getExeNameForPid
module.exports.listActiveAudioProcesses = nativeBinding.listActiveAudioProcesses
module.exports.WindowsAudioSession = nativeBinding.WindowsAudioSession
